### ISSUE TITLE
Android 不能读取数据

### ISSUE THREAD

**Issue by moioo** [ruby-china/ruby-china-app#10]
打开APP一片空白，下拉刷新也无效

```
11-20 01:47:50.698 1160-1160/org.rubychina.app E/Web Console: TypeError: Cannot read property 'items' of null
                                                                  at file:///android_asset/www/annotated_js/controllers/topics.controller.js:66:31
                                                                  at processQueue (file:///android_asset/www/lib/angular/angular.js:14567:28)
                                                                  at file:///android_asset/www/lib/angular/angular.js:14583:27
                                                                  at Scope.$eval (file:///android_asset/www/lib/angular/angular.js:15846:28)
                                                                  at Scope.$digest (file:///android_asset/www/lib/angular/angular.js:15657:31)
                                                                  at Scope.$apply (file:///android_asset/www/lib/angular/angular.js:15951:24)
                                                                  at done (file:///android_asset/www/lib/angular/angular.js:10364:47)
                                                                  at completeRequest (file:///android_asset/www/lib/angular/angular.js:10536:7)
                                                                  at XMLHttpRequest.<anonymous> (file:///android_asset/www/lib/angular/angular.js:10487:9) at file:///android_asset/www/lib/angular/angular.js:12330
```

**Comment by DotHide** [comment]
之前一直没装环境，今天我下载调试一下

**Comment by DotHide** [comment]
Android 没问题了

**Comment by moioo** [comment]
不知道是不是我的环境有问题，还是怎么的，我的还是一样。

**Comment by DotHide** [comment]
恩 可能是你的环境问题
注意在做 `$ ionic platform add android` 之前，最好先做一下 `$ gulp useref`，如果已经添加，可以先 remove 再重新 add

**Comment by moioo** [comment]
一直是按这个方法。但ios没问题 android就是取不到数据
![运行图](http://7xojdl.com1.z0.glb.clouddn.com/ruby-china-app.jpg)

**Comment by DotHide** [comment]
能取到数据了吗？没问题我就关闭拉

**Comment by moioo** [comment]
我的是不行。试了换nvm还是不行。也许是我环境有问题。你关了吧
